name: Close Stale Issues and PRs
on:
  schedule:
    - cron: 0,15,30,45 * * * *
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            In order to maintain a backlog of relevant issues, we automatically label them as stale after 1 day of inactivity.

            If this issue is still relevant to you, then please comment on this issue or remove the stale label.

            Otherwise this issue will be automatically closed in 1 days time.
          stale-pr-message: | 
            In order to maintain a backlog of relevant PRs, we automatically label them as stale after 1 day of inactivity.

            If this PR is still relevant to you, then please comment on this PR or remove the stale label.

            Otherwise this PR will be automatically closed in 1 days time.
          stale-issue-label: stale
          stale-pr-label: stale
          close-issue-message: |
            This stale issue has been automatically closed due to a lack of community activity.
            
            Either:
              * Re-open this issue, if you have sufficient permissions
              * Add a comment and `@bjlittle` who will re-open on your behalf
          close-pr-message: |
            This stale PR has been automatically closed due to a lack of community activity.
            
            Either:
              * Re-open this PR, if you have sufficient permissions
              * Add a comment and `@bjlittle` who will re-open on your behalf
          exempt-issue-labels: blocked
          exempt-pr-labels: blocked
          days-before-stale: 1
          days-before-close: 1
          remove-stale-when-updated: true
          operations-per-run: 5
