name: Only close
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: stale
          stale-pr-label: stale
          close-issue-message: |
            This stale issue has been automatically closed due to a lack of community activity.
            
            Either:
              * Re-open this issue, if you have sufficient permissions
              * Add a comment and `@bjlittle` who will re-open on your behalf
          close-pr-message: |
            This stale PR has been automatically closed due to a lack of community activity.
            
            Either:
              * Re-open this PR, if you have sufficient permissions
              * Add a comment and `@bjlittle` who will re-open on your behalf
          exempt-issue-labels: blocked
          exempt-pr-labels: blocked
          days-before-stale: -1
          days-before-close: 1
          remove-stale-when-updated: true
          operations-per-run: 5
